[build]
  command = "rm -rf .next && npm ci && npm install -g typescript && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_IGNORE_ESLINT = "1"
  CI = "false"
  NEXT_PUBLIC_API_BASE_URL = "https://digital-kudos.onrender.com/api"

[[plugins]]
  package = "@netlify/plugin-nextjs"