[build]
  command = "npm ci && npm install --save-dev typescript @types/react && NEXT_IGNORE_ESLINT=1 npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"